repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: mixed-line-ending
  - repo: local
    hooks:
      # ensure pixi environments are up to date
      # workaround for https://github.com/prefix-dev/pixi/issues/1482
      - id: pixi-install
        name: Make sure pixi envs are up to date
        entry: pixi install -e lint
        language: system
        always_run: true
        require_serial: true
        pass_filenames: false
      - id: typstyle
        name: Format Typst source code
        language: system
        entry: pixi run -e lint typstyle -i
        files: .*\.typ
      - id: typos
        name: Check for typos
        language: system
        entry: pixi run -e lint typos
        types: [text]
      - id: clippy
        name: Lint rust
        language: system
        entry: pixi run -e lint cargo clippy
        types: [rust]
        pass_filenames: false
      - id: actionling
        name: Lint GitHub Actions workflow files
        language: system
        entry: pixi run -e lint actionlint
        types: [yaml]
        files: ^\.github/workflows/
