[project]
name = "matryoshka"
version = "0.1.0"
description = "Add a short description here"
authors = ["Adrian Freund <adrian@freund.io>"]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "win-64", "osx-64", "osx-arm64"]

[system-requirements]
macos = "11.0"

[dependencies]

[tasks]
clean = { depends_on = ["rust-clean", "test-clean"] }

[feature.rust.dependencies]
rust = ">=1.79.0,<1.80"
rust-src = ">=1.79.0,<1.80"
rust-std-wasm32-unknown-unknown = ">=1.79.0,<1.80"
c-compiler = ">=1.7.0,<1.8"

[feature.rust.tasks]
build = "cargo build --release --target wasm32-unknown-unknown && cp target/wasm32-unknown-unknown/release/matryoshka.wasm ."
rust-clean = "cargo clean && rm -f matryoshka.wasm"

[feature.typst.dependencies]
typst = ">=0.11.1,<0.12"

[feature.test.dependencies]
typst-test = ">=0.0.0.post104.7babfc0,<0.0.0.1post"

[feature.test.tasks]
test = { cmd = "typst-test run", depends_on = ["build"] }
test-clean = "typst-test clean"

[feature.lint.dependencies]
typos = ">=1.22.7,<1.23"
actionlint = ">=1.7.1,<1.8"

[feature.pre-commit.dependencies]
pre-commit = ">=3.1.1,<3.2"

[feature.pre-commit.tasks]
pre-commit-install = "pre-commit install"
lint = "pre-commit run -a"

[feature.doc.dependencies]

[feature.doc.tasks]
doc = { cmd = "typst compile --root . doc/matryoshka.typ doc/matryoshka.pdf", depends_on = ["build"] }

[feature.package.dependencies]
# tar not supported on windows. Think of something better.

[feature.package.tasks]
package = { cmd = "tar -czf matryoshka.tar.gz typst.toml README.md LICENSE.txt matryoshka.wasm lib.typ", depends_on = ["build"] }

[environments]
default = { features = ["rust", "typst", "test", "package", "pre-commit"], solve-group = "dev" }
build = { features = ["rust"], solve-group = "dev" }
test = { features = ["typst", "test"], solve-group = "dev" }
lint = {features = ["rust", "lint"], solve-group = "dev" }
doc = {features = ["typst", "doc"], solve-group = "dev" }
package = { features = ["package"], solve-group = "dev" }
